############################# English ############################
[en]
languageName = "En"
title = "Techgaun Nepal - Custom Software (web, mobile, desktop) Development, CloudOps, Software Security, Architecture Design and Reviews"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Custom Software (web, mobile, desktop) Development, CloudOps, Software Security, Architecture Design and Reviews"
# copyright
copyright = "&copy; Techgaun Nepal Pvt. Ltd."



############################# Nepali ############################
# [ne-np]
# languageName = "Ne-NP"
# title = "टेकगाँउ नेपाल - Custom Software (web/mobile/desktop) Development, CloudOps, Software Security, Architecture Design and Reviews"
# contentDir = "content/deutsch" # content/german
# weight = 2
# ########### footer content ##########
# footer_menu_left = "Company"
# footer_menu_middle = "Product"
# footer_menu_right = "Support"
# footer_content = "कस्टम सफ्टवेर बिकास (वेब, मोबाईल, डेस्कटप), क्लाउड-अप्स, सफ्टवेर सुरक्षा, आर्चीटेक्चर डिजाईन तथा रिभ्यु"
# # copyright
# copyright = "&copy; टेकगाँउ नेपाल"